services:
  slackfrontend:
    build:
      context: .
      dockerfile: Dockerfile.reactUI
    ports:
      - "3000:3000"    
    depends_on:
      - db
  nodebackend: 
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports: 
      - "5000:5000"    #external:internal 
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
volumes:
   slack_db: